default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:

development:
  <<: *default
  database: db/development

test:
  <<: *default
  database: db/test

production:
  <<: *default
  database: db/production
  username: my_app
  password: <%= ENV['MY_APP_DATABASE_PASSWORD'] %>
